services:
  server:
    build: ./server
    ports:
      - "3001:3000"  # Host port 3001 mapped to container port 3000
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/smarthome
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - app-network  

  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network  

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"  # MQTT protocol port
    volumes:
      - ./mosquitto_conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - app-network  

  energy_tracker:
    build: ./devices/energy_tracker
    environment:
      - SERVER_URL=http://server:3000
      - MQTT_BROKER_URL=mqtt://mosquitto:1883
    depends_on:
      - server
      - mosquitto
    networks:
      - app-network  # Connect to app-network

  light_bulb:
    build: ./devices/light_bulb
    environment:
      - SERVER_URL=http://server:3000
      - MQTT_BROKER_URL=mqtt://mosquitto:1883
    depends_on:
      - server
      - mosquitto
    networks:
      - app-network  

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"  # Prometheus UI
    networks:
      - app-network  
    depends_on:
      - server

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3002:3000"  # Grafana UI
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  
    networks:
      - app-network  
    depends_on:
      - prometheus

volumes:
  mongo-data:
  mosquitto-data:
  mosquitto-log:
  grafana-data:
  prometheus-data:

networks:
  app-network:
    driver: bridge
